sitewomen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls', namespace='women'))
]

women/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'women'

urlpatterns = [
    path('', views.index_view, name='index')
]

women/models.py
from typing import Any
from django.db import models


class Women(models.Model):
    def __init__(self, *args, **kwargs):
        self.first_name = models.CharField('Имя', max_length=255)
        self.last_name = models.CharField('Фамилия', max_length=255)
        self.description = models.TextField('Описание', max_length=2000)
        self.category = models.ForeignKey(to='Category', on_delete=models.CASCADE, related_name='woman')
        self.tags = models.ManyToOneRel(to='Tag', on_delete=models.CASCADE, related_name='woman')
        self.husband = models.OneToOneRel(to='Husband', on_delete=models.CASCADE, related_name='wife')
        self.created_time = models.DateTimeField('Время создания', auto_now_add=True)
        self.updated_time = models.DateTimeField('Последние изменение', auto_now=True)
        self.picture = models.ImageField('Фотография',)

women/views.py
from django.shortcuts import render


def index_view(request):
    return render(request, 'women/index.html')

templates/base.html
{% load static %}
{% load women_tags %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'women/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'women/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>
{% for m in mainmenu %}
	<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
{% endfor %}
{% if user.is_authenticated %}
				<li class="last"><a href="{% url 'users:profile' %}">{{user.username}}</a> | <a href="{% url 'users:logout' %}">Выйти</a></li>
{% else %}
    <li class="last"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:register' %}">Регистрация</a></li>
{% endif %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		{% if cat_selected == 0 %}
		<li class="selected">Все категории</li>
		{% else %}
		<li><a href="{% url 'home' %}">Все категории</a></li>
		{% endif %}

		{% show_categories cat_selected %}

		<li class="share">
		<p>Наш канал</p>
		<a class="share-yt" href="https://www.youtube.com/channel/UClJzWfGWuGJL2t-3dYKcHTA/playlists" target="_blank" rel="nofollow"></a>
		</li>

		<li>{% show_all_tags %}</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

{% block navigation %}
{% endblock %}

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2023 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

women/templates/women/about.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>
{% for item in page_obj %}
<p>{{ item.pk }}: {{ item.title }}</p>
{% endfor %}

<nav>
    <ul>
        {% for p in page_obj.paginator.page_range %}
        <li>
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endfor %}
    </ul>
</nav>

{% endblock %}

women/templates/women/addpage.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Отправить</button></p>
</form>
{% endblock %}

women/templates/women/includes/nav.html
<nav>
	<a href="#">Актрисы</a> |
	<a href="#">Певицы</a> |
	<a href="#">Спортсменки</a>
</nav>

<p>{{ title2 }}</p>

women/templates/women/index.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in posts %}
			<li><div class="article-panel">
	<p class="first">Категория: {{p.cat.name}} | автор:
	{{ p.author.username|default:"неизвестен" }}</p>
	<p class="last">Дата: {{p.time_update|date:"d-m-Y H:i:s"}}</p>
    </div>
{% if p.photo %}
		<p><img class="img-article-left thumb" src="{{p.photo.url}}"></p>
{% endif %}

				<h2>{{p.title}}</h2>
    {% autoescape off %}
	{{p.content|linebreaks|truncatewords:40}}
    {% endautoescape %}
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
			</li>
	{% endfor %}
</ul>
{% endblock %}


{% block navigation %}
{% if page_obj.has_other_pages %}
<nav class="list-pages">
    <ul>
		{% if page_obj.has_previous %}
		<li class="page-num">
			<a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
		</li>
		{% endif %}

        {% for p in paginator.page_range %}
		{% if page_obj.number == p %}
		<li class="page-num page-num-selected">{{ p }}</li>
		{% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
        <li class="page-num">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
		{% endif %}
        {% endfor %}

		{% if page_obj.has_next %}
		<li class="page-num">
			<a href="?page={{ page_obj.next_page_number }}">&gt;</a>
		</li>
		{% endif %}

    </ul>
</nav>
{% endif %}
{% endblock %}

women/templates/women/list_categories.html
{% for cat in cats %}
{% if cat.id == cat_selected %}
<li class="selected">{{cat.name}}</li>
{% else %}
<li><a href="{{ cat.get_absolute_url }}">{{cat.name}}</a></li>
{% endif %}
{% endfor %}

women/templates/women/list_tags.html
{% if tags %}
    <p>Теги:</p>
    <ul class="tags-list">
        {% for t in tags %}
        <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
        {% endfor %}
    </ul>
{% endif %}

women/templates/women/post.html
{% extends 'base.html' %}

{% block breadcrumbs %}
{% if perms.women.change_women %}
<p><a href="{% url 'edit_page' post.slug %}">Редактировать</a></p>
{% endif %}

<!-- Теги -->
{% with post.tags.all as tags %}
{% if tags %}
<ul class="tags-list">
    <li>Теги:</li>
    {% for t in tags %}
    <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}
{% endblock %}

{% block content %}
<h1>{{post.title}}</h1>

{% if post.photo %}
<p><img class="img-article-left" src="{{post.photo.url}}"></p>
{% endif %}

{{post.content|linebreaks}}
{% endblock %}